output : output # path to the output folder
min_length: 20  # minimum length of the oligos
max_length: 20  # maximum length of the oligos
file_genes: "data/genes/custom_100.txt"  # path to the file containing the desired genes
num_mutations: 10  # maximum number of mutated nucleotides
num_sampled: 500  # number of sampled oligos (the final dataset size will be O(M*s*n) )
concentration: 1e-6  # strand concentrations int the tube
annotation_source: custom  # source of the genomic files, available options are [custom, ncbi, ensembl]
taxon: vertebrate_mammalian  # taxon of teh species we are intereste, oly for source: ncbi
species: Homo_sapiens # optional: species of provided annotation, leave empty if unknown
annotation_release: 110 # optional: release number of provided annotation, leave empty if unknown
n_jobs: 4  # number of available CPUs (if None the maximum number of CPUs will be used)

######### only for custom source ##########
file_annotation : data/annotations/GCF_000001405.40_GRCh38.p14_genomic.gtf  # GTF file with gene annotation
file_sequence : data/annotations/GCF_000001405.40_GRCh38.p14_genomic.fna  # FASTA file with genome sequence
files_source: NCBI # optional: original source of the genomic files
genome_assembly: GRCh38  # optional: genome assembly of provided annotation, leave empty if unknown