rain_dataset_path: data/datasets/artificial_dataset_15_100_train.csv   # path to the train dataset
validation_dataset_path: data/datasets/artificial_dataset_15_100_validation.csv   # path to the validation dataset
models_path: data/models

# fixed hyperparameters
model: rnn  # model architectura tha will be trained
input_size: 8 # dimension of the input data
features_size: 6 # number of additional features

n_trials: 50  # number of hyperparameters combinations optuna will try
n_epochs: 1000 # maximum number of epoch executed during training 
patience: 50
scheduler_factor: 0.5
scheduler_patience: 15

# tunable hyperparameters: will be sampled in the interval [min, max]
hidden_size: [32, 128] # dimension of the hidden layers
n_layers: [1, 2]  # number of stacked rnns
n_layers_mlp: [1,5] # number of layers of the mlps
nonlinearity: [relu, tanh]  # non -linear function of the RNN block
act_function: [relu, tanh]  # activation function of the mlp blocks
pool: [max, min, mean, sum]
dropout: [0, 0.5]
bidirectional: [Truem False]

batch_size: [32, 256]
lr: [0.00001, 0.01] # learning rate sampled from a loguniform distribution